# Generated by Django 5.1.5 on 2025-02-07 17:29
from django.db import migrations, models


def set_default_values(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(email__isnull=True).update(email="default@example.com")
    User.objects.filter(phone_number__isnull=True).update(phone_number="1234567890")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_phone_number",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.RunPython(set_default_values),
    ]
