[tool.black]
line-length = 100
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | __pycache__
  | migrations
  | node_modules
  | dist
  | build
)/
'''

[tool.ruff]
line-length = 100
exclude = [
  ".git",
  ".venv",
  "venv",
  "__pycache__",
  "migrations",
  "node_modules",
  "dist",
  "build",
]