# Generated by Django 5.1.6 on 2025-08-04 23:53

from django.db import migrations


def create_sizes(apps, schema_editor):
    Size = apps.get_model("products", "Size")
    sizes = ["XS", "S", "M", "L", "Oversize"]
    for size in sizes:
        Size.objects.get_or_create(name=size)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_sizes),
    ]
