# Generated by Django 5.1.6 on 2025-08-06 16:17

from django.db import migrations


def add_one_size(apps, schema_editor):
    Size = apps.get_model("products", "Size")
    Size.objects.get_or_create(name="One Size")


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_add_products"),
    ]

    operations = [
        migrations.RunPython(add_one_size),
    ]
