# Generated by Django 5.1.6 on 2025-08-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_main_image_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
