# Generated by Django 5.1.6 on 2025-08-09 05:24

from django.db import migrations, models
from django.utils.text import slugify


def fill_slugs(apps, schema_editor):
    Category = apps.get_model("products", "Category")
    for c in Category.objects.all():
        base = slugify(c.name) or "category"
        slug = base
        i = 1

        while Category.objects.filter(slug=slug).exclude(pk=c.pk).exists():
            i += 1
            slug = f"{base}-{i}"
        c.slug = slug
        c.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_category_slug"),
    ]

    operations = [
        migrations.RunPython(fill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=64, unique=True, null=False, blank=False),
        ),
    ]
