# Generated by Django 5.1.6 on 2025-08-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="product_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_price_idx",
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
