# Generated by Django 6.0 on 2025-12-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_productwishlist_stocksubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
