# Generated by Django 6.0.1 on 2026-01-15 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_collection_alter_product_main_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["name"],
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ("sort_order", "id")},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="size",
            options={
                "ordering": ["name"],
                "verbose_name": "Size",
                "verbose_name_plural": "Sizes",
            },
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productsize",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productwishlist",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="stocksubscription",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.size"
            ),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product_size"), name="uniq_cart_product_size"
            ),
        ),
        migrations.AddConstraint(
            model_name="productsize",
            constraint=models.UniqueConstraint(
                fields=("product", "size"), name="uniq_product_size"
            ),
        ),
        migrations.AddConstraint(
            model_name="productwishlist",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="uniq_wishlist_user_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("product", "user"), name="uniq_review_product_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocksubscription",
            constraint=models.UniqueConstraint(
                fields=("product", "email"), name="uniq_stocksubscription_product_email"
            ),
        ),
    ]
