# Generated by Django 6.0.1 on 2026-05-26 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_category_options_alter_collection_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterModelOptions(
            name="productwishlist",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="size",
            options={},
        ),
        migrations.AlterModelOptions(
            name="stocksubscription",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="uniq_cart_product_size",
        ),
        migrations.RemoveConstraint(
            model_name="productsize",
            name="uniq_product_size",
        ),
        migrations.RemoveConstraint(
            model_name="productwishlist",
            name="uniq_wishlist_user_product",
        ),
        migrations.RemoveConstraint(
            model_name="review",
            name="uniq_review_product_user",
        ),
        migrations.RemoveConstraint(
            model_name="stocksubscription",
            name="uniq_stocksubscription_product_email",
        ),
        migrations.RemoveField(
            model_name="product",
            name="main_image",
        ),
        migrations.AddField(
            model_name="product",
            name="care_instructions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stocksubscription",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product_size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="products.productsize",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sizes",
                to="products.size",
            ),
        ),
        migrations.AlterField(
            model_name="productwishlist",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlisted_by",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productwishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_wishlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="stocksubscription",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="stocksubscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product_size")},
        ),
        migrations.AlterUniqueTogether(
            name="productsize",
            unique_together={("product", "size")},
        ),
        migrations.AlterUniqueTogether(
            name="productwishlist",
            unique_together={("user", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("product", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="stocksubscription",
            unique_together={("product", "email")},
        ),
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
    ]
