# Generated by Django 6.0.1 on 2026-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_category_options_alter_collection_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
