# Generated by Django 6.0.1 on 2026-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_emaillog"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="custom_bust",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_cup",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_fit_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_height",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_hips",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_underbust",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_waist",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="allows_custom_sizing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("back_in_stock", "Back in stock"),
                    ("cart_reminder", "Cart reminder"),
                    ("wishlist_reminder", "Wishlist reminder"),
                    ("password_reset", "Password reset"),
                    ("order_confirmation", "Order confirmation"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
