# Generated by Django 6.0.1 on 2026-06-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_cartitem_custom_bust_cartitem_custom_cup_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ("id",)},
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
    ]
