# Generated by Django 6.0.1 on 2026-06-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
