# Generated by Django 6.0.1 on 2026-06-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_product_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("sort_order", "-created_at", "id")},
        ),
    ]
