# Generated by Django 6.0.1 on 2026-07-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="return_policy",
            field=models.CharField(
                choices=[
                    ("standard", "Standard return"),
                    ("final_sale", "Final sale"),
                    ("non_returnable_hygiene", "Non-returnable for hygiene reasons"),
                ],
                db_index=True,
                default="standard",
                help_text="Controls whether this product is eligible for a voluntary return.",
                max_length=40,
            ),
        ),
    ]
