# Generated by Django 6.0.1 on 2026-07-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_product_return_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="custom_length_cm",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_length_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_length_surcharge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="allows_custom_length",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_length_cm",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_length_surcharge",
            field=models.DecimalField(decimal_places=2, default=35, max_digits=10),
        ),
    ]
