# Generated by Django 6.0 on 2025-12-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_currency_order_email_order_status_and_more"),
        ("products", "0010_productwishlist_stocksubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.productsize",
            ),
        ),
    ]
