# Generated by Django 6.0 on 2025-12-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
