# Generated by Django 6.0 on 2025-12-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="card_brand",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="card_last4",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
    ]
