# Generated by Django 6.0 on 2026-01-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_card_brand_order_card_last4"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="card_last4",
        ),
        migrations.AddField(
            model_name="order",
            name="cardholder_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="ccard_last4",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
