# Generated by Django 6.0 on 2026-01-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_order_card_last4_order_cardholder_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="ccard_last4",
            new_name="card_last4",
        ),
    ]
