# Generated by Django 6.0 on 2026-01-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_rename_ccard_last4_order_card_last4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Card"), ("paypal", "PayPal")],
                default="card",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="size",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
