# Generated by Django 6.0 on 2026-01-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="public_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=24, null=True, unique=True
            ),
        ),
    ]
