# Generated by Django 6.0.1 on 2026-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="custom_bust",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_cup",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_fit_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_height",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_hips",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_underbust",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_waist",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
