# Generated by Django 6.0.1 on 2026-07-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_discount_amount_order_discount_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="custom_size_final_sale_acknowledged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="policy_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="policy_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="policy_version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
