# Generated by Django 6.0.1 on 2026-07-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_custom_size_final_sale_acknowledged_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
