# Generated by Django 6.0.1 on 2026-07-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_tax_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_initiated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="return_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="return_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="return_refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="return_rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="return_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="return_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No return"),
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("received", "Received"),
                    ("refund_pending", "Refund pending"),
                    ("refunded", "Refunded"),
                    ("rejected", "Rejected"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_refund_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
