# Generated by Django 6.0.1 on 2026-07-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_order_delivered_at_order_refund_initiated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="return_policy",
            field=models.CharField(
                choices=[
                    ("standard", "Standard return"),
                    ("final_sale", "Final sale"),
                    ("non_returnable_hygiene", "Non-returnable for hygiene reasons"),
                ],
                db_index=True,
                default="standard",
                help_text="Snapshot of the product return policy at the time of purchase.",
                max_length=40,
            ),
        ),
    ]
