# Generated by Django 6.0.1 on 2026-07-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_orderitem_return_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="custom_length_cm",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_length_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_length_surcharge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
