# Generated by Django 6.0.1 on 2026-09-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_orderitem_custom_length_cm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_carrier",
            field=models.CharField(blank=True, default="USPS", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
